apiVersion: apps/v1
kind: Deployment
metadata:
  name: now-frontend
  namespace: nowapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: now-frontend
  template:
    metadata:
      labels:
        app: now-frontend
    spec:
      containers:
        - name: now-frontend
          image: jinaaitmp/now-frontend:{docker_frontend_tag}
          imagePullPolicy: Always
          command: ["streamlit"]
          args: ["run", "frontend.py", "--server.port", "80", "{gateway_host}", "{gateway_port}", "{data}"]
          ports:
            - containerPort: 80
